package com.divalhr.core.tenant.api;

import com.divalhr.core.platform.error.ApiException;
import com.divalhr.core.platform.error.ErrorCode;
import com.divalhr.core.platform.idempotency.IdempotencyKeys;
import com.divalhr.core.platform.security.PlatformScoped;
import com.divalhr.core.platform.web.CorrelationId;
import com.divalhr.core.tenant.application.CreateOrganizationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import jakarta.servlet.http.HttpServletRequest;
import java.util.Map;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * Platform-scoped organization provisioning (MVP-001). The caller's {@code tenant_id} claim is
 * never read here; the new organization's ID is generated by the service.
 */
@RestController
@RequestMapping("/api/v1/organizations")
public class OrganizationController {

  private final CreateOrganizationService service;

  /**
   * Creates the controller.
   *
   * @param service use case
   */
  public OrganizationController(CreateOrganizationService service) {
    this.service = service;
  }

  /**
   * Creates an organization.
   *
   * @param idempotencyKey required idempotency key (validated by the service for stable codes)
   * @param request request body
   * @param authentication verified platform administrator
   * @param servletRequest current request (correlation ID)
   * @return 201 with the organization; replays carry {@code Idempotent-Replayed: true}
   */
  @Operation(operationId = "createOrganization")
  @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
  @ResponseStatus(HttpStatus.CREATED)
  @PlatformScoped(operation = CreateOrganizationService.OPERATION)
  public ResponseEntity<OrganizationResponse> create(
      @RequestHeader(name = IdempotencyKeys.HEADER, required = false) String idempotencyKey,
      @RequestBody CreateOrganizationRequest request,
      @Parameter(hidden = true) JwtAuthenticationToken authentication,
      @Parameter(hidden = true) HttpServletRequest servletRequest) {
    String subject = authentication.getToken().getSubject();
    if (subject == null || subject.isBlank()) {
      // Idempotency and audit are keyed on the immutable subject; refuse tokens without one.
      throw new ApiException(ErrorCode.ACCESS_DENIED, Map.of());
    }
    CreateOrganizationService.Result result =
        service.create(
            subject,
            idempotencyKey,
            request,
            String.valueOf(servletRequest.getAttribute(CorrelationId.REQUEST_ATTRIBUTE)));
    ResponseEntity.BodyBuilder response = ResponseEntity.status(HttpStatus.CREATED);
    if (result.replayed()) {
      response.header(IdempotencyKeys.REPLAYED_HEADER, "true");
    }
    return response.body(result.organization());
  }
}
