#!/usr/bin/env node
// Generates TypeScript types from the approved contracts. With --check, fails if the committed
// output is stale (the contract changed without regenerating the client).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const sources = [
  { spec: '../../../docs/API-SPEC.yaml', out: '../src/generated/core-api.ts' },
  { spec: '../../shared-contracts/openapi/ai-service.yaml', out: '../src/generated/ai-service.ts' },
];
const header = '// Generated by packages/api-client/scripts/generate.mjs. Do not edit.\n';
const check = process.argv.includes('--check');
let stale = false;

for (const { spec, out } of sources) {
  const specUrl = new URL(spec, import.meta.url);
  const outPath = fileURLToPath(new URL(out, import.meta.url));
  const content = header + astToString(await openapiTS(specUrl));
  if (check) {
    let current = '';
    try {
      current = readFileSync(outPath, 'utf8');
    } catch {
      // missing file counts as stale
    }
    if (current !== content) {
      console.error(`Stale generated client: ${out}. Run "pnpm api:generate".`);
      stale = true;
    }
  } else {
    writeFileSync(outPath, content);
    console.log(`Generated ${out}`);
  }
}
if (stale) process.exit(1);
