package com.divalhr.core.tenant.domain;

import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Organization aggregate root. Its {@code id} is the tenant identifier for every record the
 * organization will own. Immutable in MVP-001 (no editing).
 *
 * @param id organization and tenant UUID, generated by the server
 * @param name display name (customer data: never logged, audited or published in events)
 * @param countryCode ISO 3166-1 alpha-2
 * @param defaultLocale fr or en
 * @param timezone IANA time zone
 * @param currencies sorted ISO 4217 codes
 * @param status lifecycle status
 * @param createdAt UTC creation time
 * @param createdBy verified JWT subject of the creator
 */
public record Organization(
    UUID id,
    String name,
    String countryCode,
    String defaultLocale,
    String timezone,
    List<String> currencies,
    OrganizationStatus status,
    Instant createdAt,
    String createdBy) {

  /** Validates invariants that must hold regardless of the caller. */
  public Organization {
    Objects.requireNonNull(id, "id");
    Objects.requireNonNull(name, "name");
    Objects.requireNonNull(countryCode, "countryCode");
    Objects.requireNonNull(defaultLocale, "defaultLocale");
    Objects.requireNonNull(timezone, "timezone");
    Objects.requireNonNull(status, "status");
    Objects.requireNonNull(createdAt, "createdAt");
    Objects.requireNonNull(createdBy, "createdBy");
    currencies = List.copyOf(currencies.stream().sorted().toList());
    if (currencies.isEmpty()) {
      throw new IllegalArgumentException("an organization needs at least one currency");
    }
  }
}
